// Generated by CoffeeScript 1.6.3
(function(window) {
  requirejs.config({
    urlArgs: 'bust=' + (new Date()).getTime(),
    paths: {
      'jquery': 'jquery-1.10.2.min',
      'lodash': 'lodash.compat.min',
      'xregexp': 'xregexp-all-min',
      'async': 'async'
    },
    shim: {
      jquery: {
        exports: '$'
      },
      lodash: {
        exports: '_'
      },
      'jquery-lazyloadanything': {
        deps: ['jquery']
      },
      'isOnScreen': {
        deps: ['jquery']
      },
      "app": {
        deps: ['jquery', 'lodash', 'xregexp', 'jquery-lazyloadanything', 'isOnScreen'],
        exports: "_LazyLoad"
      }
    }
  });
  require(["app"], function(_LazyLoad) {
    _LazyLoad.get(window);
  });
})(window || (1, eval)("this"));
