// Generated by CoffeeScript 1.4.0

(function(global) {
  requirejs.config({
    urlArgs: 'bust=' + (new Date()).getTime(),
    paths: {
      'jquery': 'jquery-1.10.2.min',
      'underscore': 'underscore-min',
      'xregexp': 'xregexp-all-min'
    },
    shim: {
      jquery: {
        exports: '$'
      },
      underscore: {
        exports: '_'
      },
      'jquery-lazyloadanything': {
        deps: ['jquery']
      },
      'isOnScreen': {
        deps: ['jquery']
      },
      "app": {
        deps: ['jquery', 'underscore', 'xregexp', 'jquery-lazyloadanything', 'isOnScreen'],
        exports: "_LazyLoad"
      }
    }
  });
  require(["app"], function(_LazyLoad) {
    var $;
    $ = require('jquery');
    $(function() {
      return _LazyLoad.get(global);
    });
  });
})(this || (1, eval_)("this"));
